testcsv = [
    {
        "STATUS": "Done",
        "MIME_TYPE": "",
        "NAME": "test-empty-folders",
        "PUID": "",
        "EXTENSION_MISMATCH": "FALSE",
        "FILE_PATH": "C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders",
        "FORMAT_NAME": "",
        "ID": "1",
        "PARENT_ID": "",
        "EXT": "",
        "LAST_MODIFIED": "2015-07-22T13:34:37",
        "FORMAT_COUNT": "",
        "MD5_HASH": "",
        "FORMAT_VERSION": "",
        "TYPE": "Folder",
        "METHOD": "",
        "URI": "file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/",
        "SIZE": "",
    },
    {
        "STATUS": "Done",
        "MIME_TYPE": "",
        "NAME": "empty_folder_a",
        "PUID": "",
        "EXTENSION_MISMATCH": "FALSE",
        "FILE_PATH": "C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\empty_folder_a",
        "FORMAT_NAME": "",
        "ID": "2",
        "PARENT_ID": "1",
        "EXT": "",
        "LAST_MODIFIED": "2015-07-22T13:14:39",
        "FORMAT_COUNT": "",
        "MD5_HASH": "",
        "FORMAT_VERSION": "",
        "TYPE": "Folder",
        "METHOD": "",
        "URI": "file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/empty_folder_a/",
        "SIZE": "",
    },
    {
        "STATUS": "Done",
        "MIME_TYPE": "",
        "NAME": "empty_folder_b",
        "PUID": "",
        "EXTENSION_MISMATCH": "FALSE",
        "FILE_PATH": "C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\empty_folder_b",
        "FORMAT_NAME": "",
        "ID": "3",
        "PARENT_ID": "1",
        "EXT": "",
        "LAST_MODIFIED": "2015-07-22T13:14:45",
        "FORMAT_COUNT": "",
        "MD5_HASH": "",
        "FORMAT_VERSION": "",
        "TYPE": "Folder",
        "METHOD": "",
        "URI": "file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/empty_folder_b/",
        "SIZE": "",
    },
    {
        "STATUS": "Done",
        "MIME_TYPE": "",
        "NAME": "empty_folder_with_empty_folder",
        "PUID": "",
        "EXTENSION_MISMATCH": "FALSE",
        "FILE_PATH": "C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\empty_folder_with_empty_folder",
        "FORMAT_NAME": "",
        "ID": "4",
        "PARENT_ID": "1",
        "EXT": "",
        "LAST_MODIFIED": "2015-07-22T13:15:09",
        "FORMAT_COUNT": "",
        "MD5_HASH": "",
        "FORMAT_VERSION": "",
        "TYPE": "Folder",
        "METHOD": "",
        "URI": "file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/empty_folder_with_empty_folder/",
        "SIZE": "",
    },
    {
        "STATUS": "Done",
        "MIME_TYPE": "",
        "NAME": "empty_folder_inside_empty_folder",
        "PUID": "",
        "EXTENSION_MISMATCH": "FALSE",
        "FILE_PATH": "C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\empty_folder_with_empty_folder\\empty_folder_inside_empty_folder",
        "FORMAT_NAME": "",
        "ID": "5",
        "PARENT_ID": "4",
        "EXT": "",
        "LAST_MODIFIED": "2015-07-22T13:15:04",
        "FORMAT_COUNT": "",
        "MD5_HASH": "",
        "FORMAT_VERSION": "",
        "TYPE": "Folder",
        "METHOD": "",
        "URI": "file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/empty_folder_with_empty_folder/empty_folder_inside_empty_folder/",
        "SIZE": "",
    },
    {
        "STATUS": "Done",
        "MIME_TYPE": "",
        "NAME": "folder-becomes-empty-one-file",
        "PUID": "",
        "EXTENSION_MISMATCH": "FALSE",
        "FILE_PATH": "C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folder-becomes-empty-one-file",
        "FORMAT_NAME": "",
        "ID": "6",
        "PARENT_ID": "1",
        "EXT": "",
        "LAST_MODIFIED": "2015-07-22T13:15:56",
        "FORMAT_COUNT": "",
        "MD5_HASH": "",
        "FORMAT_VERSION": "",
        "TYPE": "Folder",
        "METHOD": "",
        "URI": "file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folder-becomes-empty-one-file/",
        "SIZE": "",
    },
    {
        "STATUS": "Done",
        "MIME_TYPE": "",
        "NAME": "folder-wont-empty-extension-based",
        "PUID": "",
        "EXTENSION_MISMATCH": "FALSE",
        "FILE_PATH": "C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folder-wont-empty-extension-based",
        "FORMAT_NAME": "",
        "ID": "7",
        "PARENT_ID": "1",
        "EXT": "",
        "LAST_MODIFIED": "2015-07-22T13:34:48",
        "FORMAT_COUNT": "",
        "MD5_HASH": "",
        "FORMAT_VERSION": "",
        "TYPE": "Folder",
        "METHOD": "",
        "URI": "file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folder-wont-empty-extension-based/",
        "SIZE": "",
    },
    {
        "STATUS": "Done",
        "MIME_TYPE": "",
        "NAME": "folders-become-empty-two-files-inside-other-folder",
        "PUID": "",
        "EXTENSION_MISMATCH": "FALSE",
        "FILE_PATH": "C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folders-become-empty-two-files-inside-other-folder",
        "FORMAT_NAME": "",
        "ID": "9",
        "PARENT_ID": "1",
        "EXT": "",
        "LAST_MODIFIED": "2015-07-22T13:17:06",
        "FORMAT_COUNT": "",
        "MD5_HASH": "",
        "FORMAT_VERSION": "",
        "TYPE": "Folder",
        "METHOD": "",
        "URI": "file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folders-become-empty-two-files-inside-other-folder/",
        "SIZE": "",
    },
    {
        "STATUS": "Done",
        "MIME_TYPE": "",
        "NAME": "sub-folder-becomes-empty",
        "PUID": "",
        "EXTENSION_MISMATCH": "FALSE",
        "FILE_PATH": "C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folders-become-empty-two-files-inside-other-folder\\sub-folder-becomes-empty",
        "FORMAT_NAME": "",
        "ID": "11",
        "PARENT_ID": "9",
        "EXT": "",
        "LAST_MODIFIED": "2015-07-22T13:17:29",
        "FORMAT_COUNT": "",
        "MD5_HASH": "",
        "FORMAT_VERSION": "",
        "TYPE": "Folder",
        "METHOD": "",
        "URI": "file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folders-become-empty-two-files-inside-other-folder/sub-folder-becomes-empty/",
        "SIZE": "",
    },
    {
        "STATUS": "Done",
        "MIME_TYPE": "",
        "NAME": "folders-wont-become-empty-two-files-inside-other-folder-plus-one",
        "PUID": "",
        "EXTENSION_MISMATCH": "FALSE",
        "FILE_PATH": "C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folders-wont-become-empty-two-files-inside-other-folder-plus-one",
        "FORMAT_NAME": "",
        "ID": "12",
        "PARENT_ID": "1",
        "EXT": "",
        "LAST_MODIFIED": "2015-07-22T13:17:45",
        "FORMAT_COUNT": "",
        "MD5_HASH": "",
        "FORMAT_VERSION": "",
        "TYPE": "Folder",
        "METHOD": "",
        "URI": "file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folders-wont-become-empty-two-files-inside-other-folder-plus-one/",
        "SIZE": "",
    },
    {
        "STATUS": "Done",
        "MIME_TYPE": "",
        "NAME": "sub-folder-wont-become-empty",
        "PUID": "",
        "EXTENSION_MISMATCH": "FALSE",
        "FILE_PATH": "C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folders-wont-become-empty-two-files-inside-other-folder-plus-one\\sub-folder-wont-become-empty",
        "FORMAT_NAME": "",
        "ID": "15",
        "PARENT_ID": "12",
        "EXT": "",
        "LAST_MODIFIED": "2015-07-22T13:18:27",
        "FORMAT_COUNT": "",
        "MD5_HASH": "",
        "FORMAT_VERSION": "",
        "TYPE": "Folder",
        "METHOD": "",
        "URI": "file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folders-wont-become-empty-two-files-inside-other-folder-plus-one/sub-folder-wont-become-empty/",
        "SIZE": "",
    },
    {
        "STATUS": "Done",
        "MIME_TYPE": "",
        "NAME": "thumbs.db",
        "PUID": "fmt/682",
        "EXTENSION_MISMATCH": "FALSE",
        "FILE_PATH": "C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folder-becomes-empty-one-file\\thumbs.db",
        "FORMAT_NAME": "Thumbs DB file",
        "ID": "8",
        "PARENT_ID": "6",
        "EXT": "db",
        "LAST_MODIFIED": "2015-07-22T13:15:35",
        "FORMAT_COUNT": "1",
        "MD5_HASH": "d41d8cd98f00b204e9800998ecf8427e",
        "FORMAT_VERSION": "XP",
        "TYPE": "File",
        "METHOD": "Container",
        "URI": "file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folder-becomes-empty-one-file/thumbs.db",
        "SIZE": "0",
    },
    {
        "STATUS": "Done",
        "MIME_TYPE": "",
        "NAME": "thumbs.1.db",
        "PUID": "fmt/682",
        "EXTENSION_MISMATCH": "FALSE",
        "FILE_PATH": "C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folders-become-empty-two-files-inside-other-folder\\sub-folder-becomes-empty\\thumbs.1.db",
        "FORMAT_NAME": "Thumbs DB file",
        "ID": "14",
        "PARENT_ID": "11",
        "EXT": "db",
        "LAST_MODIFIED": "2015-07-22T13:17:12",
        "FORMAT_COUNT": "1",
        "MD5_HASH": "d41d8cd98f00b204e9800998ecf8427e",
        "FORMAT_VERSION": "XP",
        "TYPE": "File",
        "METHOD": "Container",
        "URI": "file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folders-become-empty-two-files-inside-other-folder/sub-folder-becomes-empty/thumbs.1.db",
        "SIZE": "0",
    },
    {
        "STATUS": "Done",
        "MIME_TYPE": "",
        "NAME": "thumbs.2.db",
        "PUID": "fmt/682",
        "EXTENSION_MISMATCH": "FALSE",
        "FILE_PATH": "C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folders-become-empty-two-files-inside-other-folder\\sub-folder-becomes-empty\\thumbs.2.db",
        "FORMAT_NAME": "Thumbs DB file",
        "ID": "13",
        "PARENT_ID": "11",
        "EXT": "db",
        "LAST_MODIFIED": "2015-07-22T13:17:25",
        "FORMAT_COUNT": "1",
        "MD5_HASH": "d41d8cd98f00b204e9800998ecf8427e",
        "FORMAT_VERSION": "XP",
        "TYPE": "File",
        "METHOD": "Container",
        "URI": "file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folders-become-empty-two-files-inside-other-folder/sub-folder-becomes-empty/thumbs.2.db",
        "SIZE": "0",
    },
    {
        "STATUS": "Done",
        "MIME_TYPE": "",
        "NAME": "thumbs.db",
        "PUID": "fmt/682",
        "EXTENSION_MISMATCH": "FALSE",
        "FILE_PATH": "C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folder-wont-empty-extension-based\\thumbs.db",
        "FORMAT_NAME": "Thumbs DB file",
        "ID": "10",
        "PARENT_ID": "7",
        "EXT": "db",
        "LAST_MODIFIED": "2015-07-22T13:34:45",
        "FORMAT_COUNT": "1",
        "MD5_HASH": "d41d8cd98f00b204e9800998ecf8427e",
        "FORMAT_VERSION": "XP",
        "TYPE": "File",
        "METHOD": "Extension",
        "URI": "file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folder-wont-empty-extension-based/thumbs.db",
        "SIZE": "10",
    },
    {
        "STATUS": "Done",
        "MIME_TYPE": "",
        "NAME": "thumbs.2.db",
        "PUID": "fmt/682",
        "EXTENSION_MISMATCH": "FALSE",
        "FILE_PATH": "C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folders-wont-become-empty-two-files-inside-other-folder-plus-one\\sub-folder-wont-become-empty\\thumbs.2.db",
        "FORMAT_NAME": "Thumbs DB file",
        "ID": "17",
        "PARENT_ID": "15",
        "EXT": "db",
        "LAST_MODIFIED": "2015-07-22T13:17:25",
        "FORMAT_COUNT": "1",
        "MD5_HASH": "d41d8cd98f00b204e9800998ecf8427e",
        "FORMAT_VERSION": "XP",
        "TYPE": "File",
        "METHOD": "Container",
        "URI": "file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folders-wont-become-empty-two-files-inside-other-folder-plus-one/sub-folder-wont-become-empty/thumbs.2.db",
        "SIZE": "0",
    },
    {
        "STATUS": "Done",
        "MIME_TYPE": "",
        "NAME": "thumbs.1.db",
        "PUID": "fmt/682",
        "EXTENSION_MISMATCH": "FALSE",
        "FILE_PATH": "C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folders-wont-become-empty-two-files-inside-other-folder-plus-one\\sub-folder-wont-become-empty\\thumbs.1.db",
        "FORMAT_NAME": "Thumbs DB file",
        "ID": "16",
        "PARENT_ID": "15",
        "EXT": "db",
        "LAST_MODIFIED": "2015-07-22T13:17:12",
        "FORMAT_COUNT": "1",
        "MD5_HASH": "d41d8cd98f00b204e9800998ecf8427e",
        "FORMAT_VERSION": "XP",
        "TYPE": "File",
        "METHOD": "Signature",
        "URI": "file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folders-wont-become-empty-two-files-inside-other-folder-plus-one/sub-folder-wont-become-empty/thumbs.1.db",
        "SIZE": "0",
    },
    {
        "STATUS": "Done",
        "MIME_TYPE": "application/msword",
        "NAME": "word-document.doc",
        "PUID": "fmt/39",
        "EXTENSION_MISMATCH": "FALSE",
        "FILE_PATH": "C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folders-wont-become-empty-two-files-inside-other-folder-plus-one\\sub-folder-wont-become-empty\\word-document.doc",
        "FORMAT_NAME": "Microsoft Word",
        "ID": "18",
        "PARENT_ID": "15",
        "EXT": "doc",
        "LAST_MODIFIED": "2015-07-22T13:18:23",
        "FORMAT_COUNT": "8",
        "MD5_HASH": "d41d8cd98f00b204e9800998ecf8427e",
        "FORMAT_VERSION": "6.0-2003",
        "TYPE": "File",
        "METHOD": "Signature",
        "URI": "file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folders-wont-become-empty-two-files-inside-other-folder-plus-one/sub-folder-wont-become-empty/word-document.doc",
        "SIZE": "0",
    },
]

testempty = [
    {
        "STATUS": "Done",
        "MIME_TYPE": "",
        "NAME": "test-empty-folders",
        "PUID": "",
        "EXTENSION_MISMATCH": "FALSE",
        "FILE_PATH": "C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders",
        "FORMAT_NAME": "",
        "ID": "1",
        "PARENT_ID": "",
        "EXT": "",
        "LAST_MODIFIED": "2015-07-22T13:34:37",
        "FORMAT_COUNT": "",
        "MD5_HASH": "",
        "FORMAT_VERSION": "",
        "TYPE": "Folder",
        "METHOD": "",
        "URI": "file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/",
        "SIZE": "",
    },
    {
        "STATUS": "Done",
        "MIME_TYPE": "text/plain",
        "NAME": "non_empty_file_b.txt",
        "PUID": "fmt/111",
        "EXTENSION_MISMATCH": "FALSE",
        "FILE_PATH": "C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\non_empty_file_b.txt",
        "FORMAT_NAME": "",
        "ID": "2",
        "PARENT_ID": "1",
        "EXT": "txt",
        "LAST_MODIFIED": "2015-07-22T13:14:45",
        "FORMAT_COUNT": "1",
        "MD5_HASH": "",
        "FORMAT_VERSION": "",
        "TYPE": "File",
        "METHOD": "Extension",
        "URI": "file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/non_empty_file_b.txt",
        "SIZE": "4",
    },
]
